import Head from "next/head";
import { useEffect } from "react";
import Layout from "../components/layout";
import withAuth from "@/hoc/withAuth";
import { useDispatch, useSelector } from "react-redux";
import { getStats } from "@/slices/stats";
import { Spinner } from "@chakra-ui/react";

const Home = () => {
  const dispatch = useDispatch();
  const { stats, isLoadingStats } = useSelector((state) => state.stats);

  const statsData = [
    { name: "Teachers", stat: stats.teacherCount },
    { name: "Students", stat: stats.studentCount },
    { name: "Rewards", stat: stats.rewardCount },
  ];

  useEffect(() => {
    dispatch(getStats());
  }, []);

  return (
    <>
      <Head>
        <title>Edunft | Teacher Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>
          <h3 className="text-base font-semibold leading-6 text-gray-900">
            {new Date().toLocaleDateString()}
          </h3>
          <dl className="grid grid-cols-1 gap-5 mt-5 sm:grid-cols-3">
            {statsData.map((item) => (
              <div
                key={item.name}
                className="px-4 py-5 overflow-hidden bg-white border-2 border-indigo-500 rounded-lg shadow sm:p-6"
              >
                <dt className="text-sm font-medium text-gray-500 truncate">
                  {item.name}
                </dt>
                <dd className="mt-1 text-3xl font-semibold tracking-tight text-indigo-900">
                  {isLoadingStats ? <Spinner size={"xs"} /> : item.stat}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </Layout>
    </>
  );
};

export default withAuth(Home);
